[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0x36a8f9e87865164a3d55ac2e96c15e09674bd30a183f18e76a15d61815bd992c'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]